apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lambda-functions
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   
spec:
  project: lambda-project
  source:
    repoURL: https://github.com/rodrigofrs13/poc-eks-crossplane
    targetRevision: HEAD
    path: ./lambda-functions
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - SyncWaveOrder=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m