apiVersion: v1
kind: Secret
metadata:
  name: poc-crossplane-argocd-gitops-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: poc-crossplane-argocd-gitops
  url: https://github.com/rodrigofrs13/poc-eks-crossplane
  username: xxxx
  password: xxxxx